version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
      - ./storage:/app/storage
    depends_on:
      - qdrant
      - redis
      - ollama
    networks:
      - bdnb-network

  ui:
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./data:/app/data
    depends_on:
      - api
    networks:
      - bdnb-network

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage
    networks:
      - bdnb-network

  redis:
    image: redis:7.4
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - bdnb-network

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    command: ["serve"]
    networks:
      - bdnb-network

networks:
  bdnb-network:
    driver: bridge